27.08.23

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -1,9 +1,23 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
+commit_types="(UPD-[0-9]:[0-9])"
+default_commit_regex="^${commit_types}(\([a-z \-]+\))?!?: .+$"
 
-commitRegex='^(UPD-[0-9]+|merge|hotfix)'
+# Получаем сообщение фиксации
+commit_message=$(cat "$1")
 
-if ! grep -qE "$commitRegex" "$1"; then
-    echo "Aborting according commit message policy. Please specify JIRA issue UPD-XXXX."
-    exit 1
+# Проверка сообщения, если всё хорошо, коммит проходит
+if [[ "$commit_message" =~ $default_commit_regex ]]; then
+  echo -e "\e[32mCommit message meets project commit standarts...\e[0m"
+  exit 0
 fi
+
+# Выводим ошибку
+echo -e "\e[31mCommit message error\e[0m"
+echo "***********************************************************************"
+echo "Here are the  list of message type : ${commit_types}"
+echo "  <type>: <subject> max 50char ex :- fix: invalid request for login api"
+echo "  <type(<scope>):> <subject> (Max 50 char) - <scope> is option ex: - fix(user): email address is empty on profile api"
+echo "***********************************************************************"
+
+exit 1
