срань

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -1,7 +1,9 @@
 #!/bin/bash
 
-commitRegex='^(UPD-[0-9]:[0-9]+|merge|hotfix)'
+
+commitRegex='^(UPD-[0-9]+|merge|hotfix)'
+
 if ! grep -qE "$commitRegex" "$1"; then
-  echo "Aborting according commit message policy. Please specify project issue UPD-XXXX."
-  exit 1
+    echo "Aborting according commit message policy. Please specify JIRA issue UPD-XXXX."
+    exit 1
 fi
